### ISSUE TITLE
Why is sfail a string instead of a position?

### ISSUE THREAD

**Issue by Alloyed** [sqmedeiros/lpeglabel#18]
It is fairly easy to obtain a suffix string given the input string and and the suffix start position:
```
local sfail = string.sub(subject, failpos, -1)
```
it's more complex to do the inverse: here is how andremm/lua-parser does it right now:
```
local errpos = #subject-#sfail+1
```
It seems strange to me that the sfail argument returned by lpeg.match() is a string then: a parser writer concerned with performance would much rather work with positions inside a single string, instead of creating costly substrings, and positions are nice to have anyways for accurate error reporting. Is there a particular reason why lpeglabel does things this way?

**Comment by sqmedeiros** [comment]
I do not remember well. Maybe lpeglabel gives a suffix string as one of its results because I had saw andremm/lua-parser first, or because I thought it would be more convenient. 
@hishamhm have also said that it would be useful to return a position of the input string, although your proposal is to return only a position of input string, which seems more appropriate.
I intend to change this in the next release. I will leave the issue opened to remember me this.

**Comment by sqmedeiros** [comment]
I've just released a new version of LPegLabel that follows your suggestion.
